[package]
name = "rust-dmx"
version = "0.1.0"
authors = ["Christian Betz <christian.betz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmx = "0.2.1"

